### ISSUE TITLE
Codec problem

### ISSUE THREAD

**Issue by steveschulze** [dmitryduev/kowalski#7]
Hi Dima,

I am using python 3.6 and try to install kowalski. When I do 

`./kowalski.py up`

I get the following error message:

```
Traceback (most recent call last):
  File "./kowalski.py", line 194, in <module>
    getattr(sys.modules[__name__], args.command)(args)
  File "./kowalski.py", line 32, in up
    print('Spinning up Kowalski \U0001f680')
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f680' in position 21: ordinal not in range(128)

```
How can I fix this problem?

Cheers,

Steve

**Comment by dannygoldstein** [comment]
Upgrade to python 3.7.
